version: '3.9'
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_USER: chess
      MYSQL_ROOT_PASSWORD: chess
      MYSQL_DATABASE: chess_db
      MYSQL_USER: chess
      MYSQL_PASSWORD: chess
    volumes:
      - db:/var/lib/mysql
      - dbbackups:/dbbackups
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    links:
      - mysql:mysql
    depends_on:
      - mysql
    environment:
      NODE_ENV: production
      DB_NAME: chess_db
      DB_PASSWORD: chess
      DB_USER: chess
      DB_HOST: mysql
      DB_PORT: 3306
      PORT: 8010
    restart: on-failure
    command: "yarn start"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  media:
  db:
  dbbackups:
